### ISSUE TITLE
Languages not populated on obs/create

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uwadmin#15]

**Comment by paltman** [comment]
@jag3773 Is `LangCode` empty? If so, call `./manage.py sync_languages`.

**Comment by paltman** [comment]
So one reason they are probably showing in admin but not front end is the checking_level might not be set to 3.

```
    self.fields["language"].queryset = self.fields["language"].queryset.filter(checking_level=3)
    self.fields["source_text"].queryset = self.fields["source_text"].queryset.filter(checking_level=3)
```

Is this logic wrong? I might have misinterpreted what you had told me about checking levels on one of our calls.

**Comment by paltman** [comment]
To update checking levels run:

```
`./manage.py update_checking_levels`
```

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/translationDatabaseWeb#96
