### ISSUE TITLE
Source language restriction

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uwadmin#2]
In the publishing form, the source language should be restricted to only those languages that have been published to a checking level 3 (see https://api.unfoldingword.org/obs/txt/1/obs-catalog.json).

**Comment by paltman** [comment]
@jag3773 should that endpoint be used as the source of truth?  In other words, should we filter the list of languages down that match language codes in that endpoint that have a `checking_level` of `3`?

**Comment by dsm-git** [comment]
Correct, should only be en and pt-br right now.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by paltman** [comment]
@jag3773 is this for `OpenBibleStory.lang` or `OpenBibleStory.source_text` or both?

**Comment by jag3773** [comment]
Source language. A given translation can only have a source text that is at level 3.
