### ISSUE TITLE
Integrate Publish with tD

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uwadmin#3]
tD should be notified when a new language is published.

**Comment by paltman** [comment]
@jag3773 how should they be notified?  is there an email address that we should send an email notice to?

**Comment by paltman** [comment]
@jag3773 I am guessing this is an API call. what data should be created when this happens?

a `Scripture` (https://github.com/Door43/translationDatabaseWeb/blob/master/td/uw/models.py#L194-L197) record? 

@swilcox and I have discussed merging `WorkInProgress` and `Scripture` to represent generically any content being produced. Thoughts?

**Comment by jag3773** [comment]
It may be easier to have tD process
https://api.unfoldingword.org/obs/txt/1/obs-catalog.json periodically?

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by paltman** [comment]
Yup. that sounds like a good idea. I have moved this over to a task on tD
