### ISSUE TITLE
GL Identification

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uwadmin#7]
Gateway languages should be identified as such.

**Comment by paltman** [comment]
This means we need to add either another endpoint to tD or add flag to the different language nodes in http://td.unfoldingword.org/exports/langnames.json, right @jag3773?

**Comment by dsm-git** [comment]
Correct.  Probably would be nice to have in langnames.json.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
