### ISSUE TITLE
Version 1 and 2 Export

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uwadmin#9]
Translations with a source text version number that is lower than the latest source text version number, should be listed in an API endpoint of some sort.  This will allow a plugin on our Door43 server to place a notice message for that language that provides information on how to update to the latest version.

Note that English version should be considered the "latest source text version".

**Comment by paltman** [comment]
@jag3773 let's discuss this one tomorrow. I think i understand but worth more discussion to clear it up for me.

**Comment by paltman** [comment]
@jag3773 should `source_version` and `version` on `OpenBibleStory` be integers? They were originally `CharField` but it sounds like they will be treated as integers.

**Comment by jag3773** [comment]
@paltman They need to support dots, e.g. version 3.2.1

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/translationDatabaseWeb#70
